### ISSUE TITLE
Supports other LLM providers

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-langchain4j#10]
LangChain4j enables integration with [15+ LLM providers](https://docs.langchain4j.dev/integrations/language-models), allowing us to incorporate those that support the specific LangChain4j features used in this application: **Streaming**, **Tools**, and **JSON mode**. 
Potential candidates include **Google Vertex AI Gemini**, **Ollama**, and **Mistral AI**.

This task should also take into account **LLM switching**, possibly through a Maven profile.

**Comment by arey** [comment]
Test result with **Ollama** and the `llama3.3` model.

**Issue 1: toolExecutor is null**
When asking the question "How many veterinary cardiologists are there?" the LLM asks to call the function `getAllVets` which does not exist.
<details><summary>Details</summary>
<p>
2024-12-29T16:28:16.219+01:00 ERROR 58618 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException: Cannot invoke "dev.langchain4j.service.tool.ToolExecutor.execute(dev.langchain4j.agent.tool.ToolExecutionRequest, Object)" because "toolExecutor" is null] with root cause

java.lang.NullPointerException: Cannot invoke "dev.langchain4j.service.tool.ToolExecutor.execute(dev.langchain4j.agent.tool.ToolExecutionRequest, Object)" because "toolExecutor" is null
	at dev.langchain4j.service.AiServiceStreamingResponseHandler.onCompleteResponse(AiServiceStreamingResponseHandler.java:93) ~[langchain4j-1.0.0-alpha1.jar:na]
	at dev.langchain4j.model.chat.StreamingChatLanguageModel$1.onComplete(StreamingChatLanguageModel.java:69) ~[langchain4j-core-1.0.0-alpha1.jar:na]
	at dev.langchain4j.model.ollama.OllamaClient$2.onResponse(OllamaClient.java:180) ~[langchain4j-ollama-1.0.0-alpha1.jar:na]
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161) ~[retrofit-2.9.0.jar:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.12.0.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
</p>
</details> 

To remove this hallucination, we add the following command to the command prompt:
> Don't provide a function name that doesn't exist.

**Comment by arey** [comment]
I've tried the `deepseek-r1:14b` model with the LangChain4j `1.0.0-alpha1` version and I've got the following exception:
```java
2025-02-01T19:12:40.061+01:00 ERROR 93418 --- [lhost:11434/...] o.s.s.p.chat.AssistantController         : Unexpected chat error

java.lang.NullPointerException: Cannot invoke "okhttp3.ResponseBody.byteStream()" because the return value of "retrofit2.Response.body()" is null
	at dev.langchain4j.model.ollama.OllamaClient$2.onResponse(OllamaClient.java:164) ~[langchain4j-ollama-1.0.0-alpha1.jar:na]
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161) ~[retrofit-2.9.0.jar:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.12.0.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```
